@echo off
REM ============================================================================
REM  build-all.bat  -  full Realm Engine build, end to end.
REM  This Batch File was AI generated. 
REM
REM      HUMAN WRITTEN - READ THIS!
REM  Requirements (all six are verified by the [0/6] preflight, which prints
REM  every missing one before giving up - see the :check_* subroutines):
REM                1. Visual Studio 2022+ with the C++ x64 workload
REM                   (Build Tools alone are enough; toolset auto-detected)
REM                2. .NET 10 runtime (tools\Il2CppInspector.exe is a
REM                   framework-dependent .NET 10 app and will not start
REM                   without it)
REM                3. Node.js 20.12+ / npm
REM                4. RotMG Exalt installed (auto-located; or set ROTMG_PATH)
REM                5. Internet - builds.him.is serves the game metadata
REM                   (already having tools\global-metadata.decrypted.dat
REM                   satisfies this without a network probe)
REM                6. Windows x64 with ~4 GB free on this drive
REM                tools\Il2CppInspector.exe SHIPS in this repo - do NOT
REM                build Il2CppInspectorPro yourself.
REM       The rest is AI slop feel free to ignore.
REM
REM  Produces a packaged client (installer + portable, or just portable) with
REM  both freshly-built native DLLs baked in:
REM     * realm-engine.dll  (the IL2CPP hack DLL, from internal/)
REM     * winhttp.dll  (from branch client/winhttp-proxy/)  
REM  and freshly-generated IL2CPP headers for the current game build.
REM
REM  Usage:
REM     build-all.bat              installer + portable
REM     build-all.bat portable     portable exe only (faster)
REM
REM  Optional skips (set before running):
REM     set RE_SKIP_HEADERS=1      reuse existing internal/src/game/generated
REM     set RE_SKIP_XML=1          skip the (optional) game-XML download
REM ============================================================================
setlocal enableextensions
set "ROOT=%~dp0"
set "MODE=%~1"

echo.
echo ==================== Realm Engine : full build ====================

REM --- [0/6] Preflight --------------------------------------------------------
echo [0/6] Preflight checks...
REM Every check prints [ERROR] lines and KEEPS GOING, so one run surfaces all
REM missing prerequisites at once instead of only the first. PREREQ_FAIL gates
REM the build after the last check. Keep this list in sync with the header
REM comment above, SETUP.md, and the GameAssembly probe order in
REM tools/gen-il2cpp-headers.ps1.
set "PREREQ_FAIL=0"
if not defined LOCALAPPDATA set "LOCALAPPDATA=%USERPROFILE%\AppData\Local"

if not exist "%ROOT%tools\Il2CppInspector.exe" (
  echo   [ERROR] tools\Il2CppInspector.exe missing. It is committed to this
  echo          repo, so your clone is incomplete - re-clone and retry.
  set "PREREQ_FAIL=1"
) else (
  echo   [OK]   Il2CppInspector CLI present ^(committed^)
)

call :check_vs
call :check_dotnet
call :check_node
call :check_game
call :check_net
call :check_disk

if "%PREREQ_FAIL%"=="1" (
  echo.
  echo   Prerequisites failed - fix every [ERROR] above, then re-run.
  goto :fail
)

if not exist "%ROOT%tools\global-metadata.decrypted.dat" (
  echo   tools\global-metadata.decrypted.dat missing - downloading...
  curl -fSL -o "%ROOT%tools\global-metadata.decrypted.dat" "https://builds.him.is/latest/game_files/global-metadata.decrypted.dat"
  if errorlevel 1 (
    if exist "%ROOT%tools\global-metadata.decrypted.dat" del /q "%ROOT%tools\global-metadata.decrypted.dat"
    echo   [ERROR] metadata download failed.
    goto :fail
  )
  if not exist "%ROOT%tools\global-metadata.decrypted.dat" ( echo   [ERROR] metadata download produced no file. & goto :fail )
  echo   Downloaded -^> tools\global-metadata.decrypted.dat
)

call "%VSINSTALL%\VC\Auxiliary\Build\vcvars64.bat" >nul || ( echo   [ERROR] vcvars64 setup failed. & goto :fail )
echo   VS x64 environment ready (cl.exe + MSBuild).

REM --- [1/6] IL2CPP headers ---------------------------------------------------
if /I "%RE_SKIP_HEADERS%"=="1" (
  echo [1/6] Skipping IL2CPP header generation ^(RE_SKIP_HEADERS=1^).
) else (
  echo [1/6] Generating IL2CPP headers from the live game...
  powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%tools\gen-il2cpp-headers.ps1" || goto :fail
)

REM --- [2/6] realm-engine.dll -------------------------------------------------
echo [2/6] Building realm-engine.dll ^(Release^|x64^)...
REM  Release builds #error without BuildSecrets.h. build-prod.mjs writes it in
REM  step 6, but this earlier standalone build needs it too. Same fixed PUBLIC
REM  constants build-prod.mjs uses - keep the two in sync.
set "SECRETS=%ROOT%internal\src\core\ipc\BuildSecrets.h"
if not exist "%SECRETS%" (
  echo   Writing BuildSecrets.h ^(fixed public constants^)...
  > "%SECRETS%" echo #pragma once
  >>"%SECRETS%" echo // AUTO-GENERATED by build-all.bat - do not edit or commit.
  >>"%SECRETS%" echo #define BUILD_HANDSHAKE_KEY "47eb249907eb980c851fe3a7bdb56a244244bb7d465572b556e810df6827ecfb"
  >>"%SECRETS%" echo #define BUILD_PIPE_NAME "\\\\.\\pipe\\lfg-dev-bridge"
)
msbuild "%ROOT%internal\il2cpp-dll-injection.sln" /p:Configuration=Release /p:Platform=x64 /m /v:minimal /nologo || goto :fail
REM  The vcxproj's OutDir is already client\assets\, so no copy step is needed.
if not exist "%ROOT%client\assets\realm-engine.dll" ( echo   [ERROR] realm-engine.dll not produced. & goto :fail )
echo   Built -^> client\assets\realm-engine.dll

REM --- [3/6] winhttp.dll + injector.exe ---------------------------------------
REM  The proxy sources are optional: when client\winhttp-proxy\ is not present
REM  we fall back to whatever winhttp.dll is already staged in client\assets\
REM  rather than failing the whole build. Only warn if there is no shim at all,
REM  since that produces a package that silently misses the redirect.
if not exist "%ROOT%client\winhttp-proxy\build.bat" (
  echo [3/6] client\winhttp-proxy\build.bat not present - skipping winhttp.dll build.
  if exist "%ROOT%client\assets\winhttp.dll" (
    echo   Using the winhttp.dll already staged in client\assets\.
  ) else (
    echo   [WARN] No winhttp.dll staged in client\assets\ either.
    echo   [WARN] The packaged client will ship without the network shim.
  )
) else (
  echo [3/6] Building winhttp.dll ^(source shim^)...
  REM  build.bat is invoked by explicit path, not by bare name: cmd only
  REM  searches the working directory when NoDefaultCurrentDirectoryInExePath
  REM  is unset, and it is set on some machines. The pushd still matters --
  REM  build.bat resolves its own inputs relative to the working directory.
  pushd "%ROOT%client\winhttp-proxy"
  call ".\build.bat" || ( popd & goto :fail )
  popd
  if not exist "%ROOT%client\winhttp-proxy\winhttp.dll" ( echo   [ERROR] winhttp.dll not produced. & goto :fail )
  copy /y "%ROOT%client\winhttp-proxy\winhttp.dll" "%ROOT%client\assets\winhttp.dll" >nul
  echo   Staged -^> client\assets\winhttp.dll
)

REM  injector.exe — CreateRemoteThread loader that src/native/injector.ts spawns
REM  to inject realm-engine.dll. Single translation unit, Windows.h + CRT only.
REM  It is NOT built by `npm run dist:installer`, so without this step the
REM  packaged client ships whatever injector.exe happens to be lying in assets\.
REM  Console subsystem is deliberate: it prints a JSON result line, and it is
REM  spawned with windowsHide so no window appears.
echo [3/6] Building injector.exe...
if not exist "%ROOT%internal\tools\injector\injector.cpp" (
  echo   [ERROR] internal\tools\injector\injector.cpp not found. & goto :fail
)
pushd "%ROOT%client\assets"
REM  UNICODE is required: injector.cpp calls LookupPrivilegeValueW but passes
REM  SE_DEBUG_NAME, a TCHAR macro that expands narrow without it, so the file
REM  will not compile. VS C++ projects define it by default; bare cl does not.
REM  advapi32 for the token APIs (OpenProcessToken, AdjustTokenPrivileges,
REM  LookupPrivilegeValueW); everything else in the file is kernel32.
cl /nologo /O2 /MT /W3 /EHsc /std:c++17 /DWIN32_LEAN_AND_MEAN /DUNICODE /D_UNICODE ^
   "%ROOT%internal\tools\injector\injector.cpp" /Fe:injector.exe ^
   /link advapi32.lib || ( popd & goto :fail )
del /q injector.obj 2>nul
popd
if not exist "%ROOT%client\assets\injector.exe" ( echo   [ERROR] injector.exe not produced. & goto :fail )
echo   Staged -^> client\assets\injector.exe

REM --- [4/6] Client dependencies ---------------------------------------------
pushd "%ROOT%client"
if not exist "node_modules\.bin\tsc.cmd" (
  echo [4/6] Installing client dependencies ^(npm install^)...
  call npm install || ( popd & goto :fail )
) else (
  echo [4/6] node_modules present - skipping npm install.
)

REM --- [5/6] Optional game XML -----------------------------------------------
if /I "%RE_SKIP_XML%"=="1" (
  echo [5/6] Skipping game-XML download ^(RE_SKIP_XML=1^).
) else (
  echo [5/6] Downloading game XML ^(best-effort^)...
  call npm run download-game-xml -- --dir ./data
  call npm run download-game-xml
)

REM --- [6/6] Package client ---------------------------------------------------
if /I "%MODE%"=="portable" (
  echo [6/6] Packaging client ^(portable^)...
  call npm run dist:portable
) else (
  echo [6/6] Packaging client ^(installer + portable^)...
  call npm run dist
)
if errorlevel 1 ( popd & goto :fail )
popd

echo.
echo ==================== BUILD OK ====================
echo Output: %ROOT%client\release
dir /b "%ROOT%client\release\*.exe" 2>nul
echo.
endlocal & exit /b 0

:fail
echo.
echo ==================== BUILD FAILED ====================
echo See the [ERROR] lines above.
endlocal & exit /b 1

REM ===========================================================================
REM Preflight subroutines (one per prerequisite). Each prints [OK] or [ERROR]
REM and sets PREREQ_FAIL=1 on failure; none aborts on its own so a single run
REM reports every missing prerequisite. Subroutines read variables set by
REM earlier statements - never set and read the same var inside one
REM parenthesized block.
REM ===========================================================================

:check_vs
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
set "VSINSTALL="
if exist "%VSWHERE%" for /f "usebackq tokens=*" %%i in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALL=%%i"
if defined VSINSTALL (
  echo   [OK]   1/6 Visual Studio C++ x64: %VSINSTALL%
  goto :eof
)
echo   [ERROR] 1/6 Visual Studio 2022+ with the C++ x64 workload not found.
echo          Install "Visual Studio Build Tools 2022" + "Desktop development
echo          with C++" (Build Tools alone are enough):
echo          https://visualstudio.microsoft.com/downloads/
set "PREREQ_FAIL=1"
goto :eof

:check_dotnet
where dotnet >nul 2>nul
if errorlevel 1 (
  echo   [ERROR] 2/6 .NET 10 runtime required - dotnet not on PATH.
  echo          tools\Il2CppInspector.exe is a .NET 10 app and will not run
echo          without it. Install x64 .NET 10 Desktop Runtime:
  echo          https://dotnet.microsoft.com/download/dotnet/10.0
  set "PREREQ_FAIL=1"
  goto :eof
)
dotnet --list-runtimes 2>nul | findstr /C:"Microsoft.NETCore.App 10." >nul
if errorlevel 1 (
  echo   [ERROR] 2/6 .NET 10 runtime required. Installed .NET runtimes:
  dotnet --list-runtimes 2>nul | findstr /C:"Microsoft.NETCore.App"
  echo          Install x64 .NET 10 Desktop Runtime:
  echo          https://dotnet.microsoft.com/download/dotnet/10.0
  set "PREREQ_FAIL=1"
  goto :eof
)
echo   [OK]   2/6 .NET 10 runtime
goto :eof

:check_node
where npm >nul 2>nul
if errorlevel 1 (
  echo   [ERROR] 3/6 Node.js/npm not on PATH.
  echo          Install the current LTS ^(20.12 or newer^): https://nodejs.org
  set "PREREQ_FAIL=1"
  goto :eof
)
set "NODE_MAJOR="
set "NODE_MINOR="
for /f "tokens=1-2 delims=." %%a in ('node -p process.versions.node 2^>nul') do (
  set "NODE_MAJOR=%%a"
  set "NODE_MINOR=%%b"
)
if not defined NODE_MAJOR (
  echo   [ERROR] 3/6 npm found but node would not run.
  echo          Reinstall Node.js LTS: https://nodejs.org
  set "PREREQ_FAIL=1"
  goto :eof
)
REM strip leading zeros from the minor so "if LSS" never sees an octal "09"
for /f "tokens=* delims=0" %%z in ("%NODE_MINOR%") do set "NODE_MINOR=%%z"
if not defined NODE_MINOR set "NODE_MINOR=0"
set "NODE_BAD="
if %NODE_MAJOR% LSS 20 set "NODE_BAD=1"
if %NODE_MAJOR% EQU 20 if %NODE_MINOR% LSS 12 set "NODE_BAD=1"
if defined NODE_BAD (
  echo   [ERROR] 3/6 Node 20.12+ required, found %NODE_MAJOR%.%NODE_MINOR%.x.
  echo          Update Node.js: https://nodejs.org
  set "PREREQ_FAIL=1"
  goto :eof
)
echo   [OK]   3/6 Node %NODE_MAJOR%.%NODE_MINOR% + npm
goto :eof

:check_game
REM Same probe order as tools/gen-il2cpp-headers.ps1 (ExaltFinder) - keep the
REM two lists in sync.
set "GAME_DIR="
if defined ROTMG_PATH (
  if exist "%ROTMG_PATH%\GameAssembly.dll" if exist "%ROTMG_PATH%\RotMG Exalt.exe" set "GAME_DIR=%ROTMG_PATH%"
)
if not defined GAME_DIR for %%D in ("%LOCALAPPDATA%\RealmOfTheMadGod\Production" "%USERPROFILE%\Documents\RealmOfTheMadGod\Production" "C:\Program Files (x86)\Steam\steamapps\common\RotMG Exalt" "C:\Program Files\Steam\steamapps\common\RotMG Exalt" "D:\Steam\steamapps\common\RotMG Exalt" "D:\SteamLibrary\steamapps\common\RotMG Exalt" "E:\Steam\steamapps\common\RotMG Exalt" "E:\SteamLibrary\steamapps\common\RotMG Exalt") do (
  if exist "%%~D\GameAssembly.dll" if exist "%%~D\RotMG Exalt.exe" set "GAME_DIR=%%~D"
)
if defined GAME_DIR (
  echo   [OK]   4/6 RotMG Exalt: %GAME_DIR%
  goto :eof
)
echo   [ERROR] 4/6 RotMG Exalt install not found (GameAssembly.dll).
echo          Install the game, or set ROTMG_PATH to the folder that contains
echo          GameAssembly.dll (custom Steam library drives are not probed).
set "PREREQ_FAIL=1"
goto :eof

:check_net
if exist "%ROOT%tools\global-metadata.decrypted.dat" (
  echo   [OK]   5/6 game metadata cached locally ^(no download needed^)
  goto :eof
)
curl -fsI --max-time 15 -o nul "https://builds.him.is/latest/game_files/global-metadata.decrypted.dat"
if errorlevel 1 (
  echo   [ERROR] 5/6 cannot reach builds.him.is - the game metadata has to
  echo          be downloaded from there. Check your connection/firewall.
  set "PREREQ_FAIL=1"
  goto :eof
)
echo   [OK]   5/6 builds.him.is reachable
goto :eof

:check_disk
if /i not "%PROCESSOR_ARCHITECTURE%"=="AMD64" (
  echo   [ERROR] 6/6 Windows x64 required - this machine reports %PROCESSOR_ARCHITECTURE%.
  set "PREREQ_FAIL=1"
  goto :eof
)
set "FREE_GB="
for /f "usebackq delims=" %%f in (`powershell -NoProfile -Command "[int]((Get-PSDrive -Name '%ROOT:~0,1%').Free / 1GB)"`) do set "FREE_GB=%%f"
if not defined FREE_GB (
  echo   [WARN] 6/6 could not determine free disk space - continuing anyway
  goto :eof
)
if %FREE_GB% LSS 4 (
  echo   [ERROR] 6/6 only %FREE_GB% GB free on %ROOT:~0,1%: - the build needs
  echo          ~4 GB ^(node_modules + Electron cache + two ~160 MB packages^).
  set "PREREQ_FAIL=1"
  goto :eof
)
echo   [OK]   6/6 %FREE_GB% GB free on %ROOT:~0,1%: ^(x64 Windows^)
goto :eof
