import {describe,it,expect} from 'vitest';
import {DamageCoverage,scriptEvidenceRecord} from '../runtimeEvidence.js';
describe('conservative damage stream spans',()=>{
 it('requires map, ready self and successfully flushed parsed observations',()=>{const c=new DamageCoverage(),a={};c.packet(a,1,'NEWTICK',true,true,0);expect(c.flushed(2,0)).toBeNull();c.packet(a,3,'MAPINFO',true,false,0);c.packet(a,4,'NEWTICK',true,true,0);c.packet(a,100,'NEWTICK',true,true,0);expect(c.flushed(101,0)).toMatchObject({start_ms:4,end_ms:100,stream:'packet_damage'});});
 it.each(['parse','writer','context','disconnect','gap','map','client'])('does not bridge %s failure',reason=>{const c=new DamageCoverage(),a={};c.packet(a,1,'MAPINFO',true,true,0);c.packet(a,50,'NEWTICK',true,true,0);if(reason==='parse')c.packet(a,60,'UNKNOWN',false,true,0);if(reason==='writer'||reason==='context')expect(c.flushed(60,1)).toBeNull();if(reason==='disconnect')c.disconnect(a);if(reason==='gap')c.packet(a,5000,'NEWTICK',true,true,0);if(reason==='map')c.packet(a,60,'MAPINFO',true,true,0);if(reason==='client')c.packet({},60,'NEWTICK',true,true,0);expect(c.flushed(61,reason==='writer'||reason==='context'?1:0)).toBeNull();});
 it('emits contiguous verified intervals without inflating end to timer time',()=>{const c=new DamageCoverage(),a={};c.packet(a,1,'MAPINFO',true,true,0);c.packet(a,50,'NEWTICK',true,true,0);expect(c.flushed(500,0)?.end_ms).toBe(50);c.packet(a,100,'NEWTICK',true,true,0);expect(c.flushed(501,0)).toMatchObject({start_ms:50,end_ms:100});});
});
it('entry dispatch states scope without inventing assignment or transitive verification',()=>{expect(scriptEvidenceRecord({kind:'dispatch',script_id:'farmer',entry_sha256:'a'.repeat(64),arm:'candidate'},1)).toMatchObject({k:'script_dispatch',hash_scope:'entry_module',transitive_imports_verified:false});expect(scriptEvidenceRecord({kind:'dispatch',script_id:'farmer',entry_sha256:'a'.repeat(64)},1)).not.toHaveProperty('arm');});
it('structured observations are allowlisted, bounded and marked untrusted',()=>{const r=scriptEvidenceRecord({kind:'log',script_id:'probe',line:'[probe] CONDITION_WITNESS {"event":"branch_enter","nativeSequence":14,"token":"secret","nativeHandled":true}'},1);expect(r).toMatchObject({k:'script_observation',payload:{event:'branch_enter',nativeSequence:14},trust:'script_report_requires_independent_join'});expect(JSON.stringify(r)).not.toContain('secret');expect(JSON.stringify(r)).not.toContain('nativeHandled');expect(scriptEvidenceRecord({kind:'log',script_id:'probe',line:'arbitrary secret'},1)).toBeNull();});
it('keeps existing observer geometry with explicit source age unknown and strips nested secrets',()=>{const record=scriptEvidenceRecord({kind:'log',script_id:'farmer',line:'FARMER_COMBAT_OBSERVER '+JSON.stringify({kind:'observation',t:9,player:{position:{x:1,y:2},token:'secret'},selected:{objectId:3,objectType:4,source:'bossEncounter',observed:{objectId:3,hp:5,name:'private'}},nearbyEnemies:[{objectId:3,position:{x:2,y:3},secret:'no'}]})},10);expect(record).toMatchObject({payload:{player:{position:{x:1,y:2}},selected:{objectId:3,source:'bossEncounter'},sampleAgeMs:null}});expect(JSON.stringify(record)).not.toMatch(/secret|private/);});
it('does not create damage coverage from an unparsed MAPINFO followed by parsed traffic',()=>{const c=new DamageCoverage(),a={};c.packet(a,1,'MAPINFO',false,true,0);c.packet(a,100,'NEWTICK',true,true,0);c.packet(a,200,'NEWTICK',true,true,0);expect(c.flushed(201,0)).toBeNull();});
