#!/usr/bin/env bash
# Compile the internal DLL from WSL by driving the Windows VS2022 MSBuild.
#
# Verified working: builds x64/Debug version.dll clean (0 warnings, 0 errors)
# from a Debian WSL2 shell against the Windows-side Visual Studio 2022 install.
#
# Two gotchas this wrapper handles, discovered the hard way:
#   1. MSVC cl.exe cannot write the PCH / obj intermediates onto the
#      \\wsl.localhost\ 9P path (C1083 on version.pch). Fix: redirect IntDir
#      and OutDir onto the native C: drive. Source is still read over UNC fine.
#   2. Release (_VERSION, no _DEBUG) hard-requires internal/.../BuildSecrets.h
#      (the shared HMAC handshake key, generated by build-prod.mjs, uncommitted).
#      Debug uses the committed dev-only key, so it compiles with no secrets.
#      => Default here is Debug. Pass "Release" only on a host that has
#         BuildSecrets.h.
#
# Prereq: the generated IL2CPP headers must be present in
#   internal/src/game/generated/  (il2cpp-types.h, il2cpp-functions.h,
#   il2cpp-types-ptr.h, il2cpp-api-functions.h, il2cpp-api-functions-ptr.h,
#   il2cpp-metadata-version.h). They are ~94 MB, gitignored, and regenerated
#   per game build with Il2CppInspectorPro (see repo SETUP.md).
#
# Usage:  internal/tools/wsl-build.sh [Debug|Release]
set -euo pipefail

CONFIG="${1:-Debug}"
DISTRO="${WSL_DISTRO_NAME:-Debian}"
REPO_WIN="\\\\wsl.localhost\\${DISTRO}\\home\\jesse\\realm-engine-client\\internal"
SLN="${REPO_WIN}\\il2cpp-dll-injection.sln"
OUT="C:\\rebuild\\${CONFIG}"

VSWHERE="/mnt/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
MSBUILD="$("$VSWHERE" -latest -requires Microsoft.Component.MSBuild \
  -find 'MSBuild\**\Bin\MSBuild.exe' | tr -d '\r')"
MSBUILD_WSL="$(printf '%s' "$MSBUILD" | sed 's|C:|/mnt/c|; s|\\|/|g')"

GEN="$(dirname "$0")/../src/game/generated/il2cpp-types.h"
if [[ ! -f "$GEN" ]]; then
  echo "ERROR: generated IL2CPP headers missing (internal/src/game/generated/)." >&2
  echo "       Regenerate per SETUP.md before building." >&2
  exit 1
fi

echo "=== Building ${CONFIG} | x64  (out: ${OUT}) ==="
"$MSBUILD_WSL" "$SLN" \
  /p:Configuration="${CONFIG}" /p:Platform=x64 \
  /p:IntDir="${OUT}\\obj\\" /p:OutDir="${OUT}\\bin\\" \
  /m /v:minimal /nologo /clp:Summary
echo "=== version.dll -> ${OUT}\\bin\\version.dll ==="
