import { expect, it, vi } from 'vitest';
import { MovementController } from '../MovementController.js';
import { sendDllFeature } from '../../../../bridge/DllFeatureBus.js';
import type { BridgeDeps } from '../../BridgeDeps.js';
import { publishNavigationStatus } from '../../../../bridge/DllNavigationBus.js';
vi.mock('../../../../bridge/DllFeatureBus.js', () => ({ sendDllFeature: vi.fn(() => true) }));
it('accepts only active point statuses and invalidates cleared and superseded requests', () => {
  const movement = new MovementController({ clientRef: { current: { connected: true } } } as unknown as BridgeDeps);
  const received = vi.fn();
  const removeThrower = movement.onNavigationStatus(() => { throw new Error('script failure'); });
  const unsubscribe = movement.onNavigationStatus(received);
  movement.navigateTo(10, 20);
  const firstId = Number(vi.mocked(sendDllFeature).mock.calls.at(-1)![1].toString().split(',')[0]);
  movement.navigateTo(30, 40);
  const secondId = Number(vi.mocked(sendDllFeature).mock.calls.at(-1)![1].toString().split(',')[0]);
  const status = { goalKind: 'point' as const, goalId: firstId, generation: 1, state: 'unreachable' as const, reason: 'stuck' };
  publishNavigationStatus(status);
  expect(received).not.toHaveBeenCalled();
  publishNavigationStatus({ ...status, goalKind: 'ring', goalId: secondId });
  expect(received).not.toHaveBeenCalled();
  publishNavigationStatus({ ...status, goalId: secondId, state: 'partial', generation: 3 });
  expect(received).toHaveBeenCalledOnce();
  publishNavigationStatus({ ...status, goalId: secondId, generation: 2 });
  expect(received).toHaveBeenCalledOnce();
  publishNavigationStatus({ ...status, goalId: secondId, generation: 3 });
  expect(received).toHaveBeenLastCalledWith(expect.objectContaining({ state: 'unreachable', position: { x: 30, y: 40 } }));
  expect(movement.getTarget()).toBeNull();
  movement.navigateTo(50, 60);
  movement.clearWaypoint();
  publishNavigationStatus({ ...status, goalId: secondId, generation: 3 });
  expect(received).toHaveBeenCalledTimes(2);
  unsubscribe();
  removeThrower();
});
it('clears native waypoints even with no script target cached', () => {
  const movement = new MovementController({ clientRef: { current: { connected: true } } } as unknown as BridgeDeps);
  movement.clearWaypoint();
  expect(sendDllFeature).toHaveBeenCalledWith('walkTargetActive', false);
  movement.navigateTo(10, 20); movement.clearWaypoint();
  expect(movement.getTarget()).toBeNull();
  expect(sendDllFeature).toHaveBeenLastCalledWith('walkTargetActive', false);
});
it('invalidates request correlation across same-name map resets', () => {
  const hooks = new Map<string, () => void>();
  const movement = new MovementController({ clientRef: { current: { connected: true } },
    proxy: { hookPacket: (name: string, callback: () => void) => hooks.set(name, callback) } } as unknown as BridgeDeps);
  const received = vi.fn();
  const unsubscribe = movement.onNavigationStatus(received);
  movement.navigateTo(10, 20);
  const goalId = Number(vi.mocked(sendDllFeature).mock.calls.at(-1)![1].toString().split(',')[0]);
  hooks.get('MAPINFO')!();
  publishNavigationStatus({ goalKind: 'point', goalId, generation: 1, state: 'unreachable', reason: 'map_changed' });
  expect(received).not.toHaveBeenCalled();
  expect(movement.getTarget()).toBeNull();
  unsubscribe();
});
it('keeps reaffirmed goal identity stable and accepts native map reset for an early new goal', () => {
  const movement = new MovementController({ clientRef: { current: { connected: true } } } as unknown as BridgeDeps);
  const received = vi.fn();
  const unsubscribe = movement.onNavigationStatus(received);
  movement.navigateTo(10, 20);
  const command = vi.mocked(sendDllFeature).mock.calls.at(-1)!;
  const count = vi.mocked(sendDllFeature).mock.calls.length;
  expect(movement.navigateTo(10.1, 20)).toBe(true);
  expect(vi.mocked(sendDllFeature).mock.calls).toHaveLength(count);
  const goalId = Number(String(command[1]).split(',')[0]);
  publishNavigationStatus({ goalKind: 'point', goalId, generation: 4, state: 'unreachable', reason: 'map_changed' });
  expect(received).toHaveBeenCalledOnce();
  expect(movement.getTarget()).toBeNull();
  movement.navigateTo(10, 20);
  expect(Number(String(vi.mocked(sendDllFeature).mock.calls.at(-1)![1]).split(',')[0])).toBeGreaterThan(goalId);
  unsubscribe();
});
it('sends a bounded atomic group preference without changing aim or waypoint ownership', () => {
  vi.mocked(sendDllFeature).mockClear();
  const movement = new MovementController({ clientRef: { current: { connected: true } } } as unknown as BridgeDeps);
  expect(movement.setGroupPreference(42, 10, 20)).toBe(true);
  expect(sendDllFeature).toHaveBeenCalledOnce();
  expect(sendDllFeature).toHaveBeenCalledWith('scriptMbcGroupGoal', '42,10,20');
  expect(movement.setGroupPreference(42, NaN, 20)).toBe(false);
  movement.clearGroupPreference();
  expect(sendDllFeature).toHaveBeenLastCalledWith('scriptMbcGroupGoal', '');
});
