// Generated C++ file by Il2CppInspectorPro - http://www.djkaty.com - https://github.com/djkaty
      // IL2CPP application data

      #pragma once

      #include <cstdint>

      // Application-specific types
      #include "il2cpp-types.h"

      // NOTE: Il2CppGCHandle and Il2CppAndroidUpStateFunc are emitted directly by
      // il2cpp-types.h as generated by the current HeaderGen toolchain, so no
      // manual typedefs are needed here (they only ever back the generated
      // il2cpp-api-functions.h declarations, which are self-consistent with the
      // generated types). If you ever regenerate with an older generator variant
      // that omits them, re-add the fallbacks behind a guard.

      // IL2CPP APIs
      #define DO_API(r, n, p) extern r (*n) p
      #include "il2cpp-api-functions.h"
      #undef DO_API

      // Application-specific functions
      #define DO_APP_FUNC(a, r, n, p) extern r (*n) p
      #define DO_APP_FUNC_METHODINFO(a, n) extern struct MethodInfo ** n
      namespace app {
      #include "il2cpp-functions.h"
      }
      #undef DO_APP_FUNC
      #undef DO_APP_FUNC_METHODINFO

      // TypeInfo pointers
      #define DO_TYPEDEF(a, n) extern n ## __Class** n ## __TypeInfo
      namespace app {
      #include "il2cpp-types-ptr.h"
      }
      #undef DO_TYPEDEF